---
name: New term request form
description: A request for a new term to be added to the vocabulary.
title: "[NTR]: "
labels: new_term_request
body: 
- type: markdown
  attributes: 
    value: "## Thanks for suggesting a new term"
- type: input
  id: prefLabel
  attributes: 
    label: new term label
    description: the name of the term in the ontology, use a camel case name and no punctuation 
    placeholder: label
  validations:
    required: true
- type: textarea
  id: definition
  attributes:
    label: definition
    description: textual definition
    placeholder: definition
  validations:
    required: true
- type: input
  id: sourceURI
  attributes: 
    label: source of definition (URI)
    description: URI for the source of the definition
    placeholder: URI
- type: textarea
  id: source
  attributes:
    label: source of definition (citation)
    description: citation for the source of the definition
    placeholder: citation
- type: input
  id: broader
  attributes: 
    label: broader term 
    description: broader term or super-class
    placeholder: label
- type: textarea
  id: relation
  attributes: 
    label: related term(s) 
    description: related term or class in this vocabulary
    placeholder: label(s) (one per line)
- type: textarea
  id: match
  attributes: 
    label: mapping term 
    description: related term or class in another vocabulary
    placeholder: URI(s) (one per line)
- type: textarea
  id: altLabel
  attributes: 
    label: synonym or alternative label
    description: label with no punctuation except `-` and `_`
    placeholder: label(s) (one per line)
- type: textarea
  id: scopeNote
  attributes:
    label: usage- or scope-note
    description: scope note
    placeholder: note
- type: input
  id: submitter
  attributes:
    label: submitter name
    description: the name of the submitter of the new term request
    placeholder: full name
- type: textarea
  id: comment
  attributes:
    label: additional information
    description: comment
    placeholder: comment