name: Generate documentation

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ontospy[FULL]

    - name: Generate docs
      run: |
        ontospy gendocs -o docs --type 2 --nobrowser mod-v1.4_ontology.owl

    - name: Commit and push
      run: |
        git config --global user.name 'Clément Jonquet'
        git config --global user.email 'jonquet@lirmm.fr'
        git add -A && git commit -m "Automatically generate documentation from OWL ontology file using Ontospy gendocs."
        git push
    
